include: dinov2/configs/ssl_default_config.yaml

train:
  batch_size_per_gpu: 96          # H100 80 GB can hold this with FSDP
  num_workers: 12
  OFFICIAL_EPOCH_LENGTH: 1250     

student:
  arch: vit_large
  patch_size: 16
  block_chunks: 0                 # unlimited chunks on big VRAM
  drop_path_rate: 0.3             # default

crops:
  local_crops_number: 8           # full multi-crop
  global_crops_size: 224
  local_crops_size: 96

optim:
  epochs: 30                      # 500 -> 30 for testing purposes
  warmup_epochs: 3               # compress 10-epoch warm-up
  base_lr: 0.004
  lr: 0.
  weight_decay: 0.04
  weight_decay_end: 0.4
  clip_grad: 3.0
  layerwise_decay: 0.9

teacher:
  warmup_teacher_temp_epochs: 5   # was 30; match shorter run
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  momentum_teacher: 0.992
  final_momentum_teacher: 1.0

evaluation:
  eval_period_iterations: 5000
