
#dino:
#   head_n_prototypes: 131072
#   head_bottleneck_dim: 384
ibot:
  separate_head: true
#   head_n_prototypes: 131072
train:
  dataset_path: ImageNet:split=TRAIN
  batch_size_per_gpu: 64
#centering: sinkhorn_knopp

student:
  arch: vit_small
  block_chunks: 4
  num_register_tokens: 4
  drop_rate_path: 0.4
teacher:
  momentum_teacher: 0.994
optim:
  weight_decay_end: 0.2
  layerwise_decay: 1.0
  
